name: ecomm-monolithic-infra
description: A typescript ecomm project to upload
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
